name: Generating Reasonable IPv4 Ranges

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fetch-and-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Zsh and Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl zsh python3-pip
        pip3 install cidrmerge

    - name: Run the IP fetching and merging script
      run: |
        rm -f unmerged-temp.txt reasonable-ipv4-merged.txt

        ipv4_list=(
          "https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/digitalocean/ipv4.txt"
          "https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/facebook/ipv4.txt"
          "https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/github/ipv4.txt"
          "https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/google/ipv4.txt"
          "https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/openai/ipv4.txt"
          "https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/cloudflare/ipv4.txt"
        )

        for url in "${ipv4_list[@]}"; do
          echo "Fetching $url"
          if ! curl -s "$url" >> unmerged-temp.txt; then
            echo "Error: Failed to fetch $url" >&2
          fi
        done

        cat unmerged-temp.txt | cidrmerge | sort -V > reasonable-ipv4-merged.txt

    - name: Upload merged file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: merged-ipv4
        path: reasonable-ipv4-merged.txt
