name: Update Reasonable IPv4 Ranges

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl python3-venv
          python3 -m venv .venv
          source .venv/bin/activate
          pip install netaddr

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch
        run: |
          ipv4_list=(
            "https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/digitalocean/ipv4.txt"
            "https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/facebook/ipv4.txt"
            "https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/github/ipv4.txt"
            "https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/google/ipv4.txt"
            "https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/openai/ipv4.txt"
            "https://raw.githubusercontent.com/lord-alfred/ipranges/refs/heads/main/cloudflare/ipv4.txt"
          )

          for url in "${ipv4_list[@]}"; do
            echo "Fetching from $url"
            curl -s $url >> unmerged.txt || echo "Error: Failed to fetch $url"
          done

          cat unmerged.txt

      - name: Merge
        run: |
          python merge.py --source=unmerged.txt | sort -V > reasonable-ipv4.txt

      - name: Update Repository
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add reasonable-ipv4.txt unmerged.txt
          git commit -m "Update reasonable-ipv4.txt"
          git push
